workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

image: $CI_REGISTRY_IMAGE/ubuntu2404-php83-node24:1

stages: [test]

test:
  before_script:
    - composer config -g github-oauth.github.com "$GITHUB_TOKEN"
    - composer config -g --list | grep github-oauth || true
  script:
    - php -v
    - node -v
    - composer --version
    - composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader --classmap-authoritative -vvv
  # artifacts:
  #   paths:
  #     - wp-content
  #   expire_in: 1 week
  #   when: always